#Try to find ORB_SLAM2 library
#
# Once done this will define
#
#  ORB_SLAM2_FOUND - system has eigen lib with correct version
#  ORB_SLAM2_INCLUDE_DIRS - the eigen include directory
#  ORB_SLAM2_LIBRARIES - the ORB_SLAM2 and other libraries

find_library(ORB_SLAM2_LIBRARY NAMES ORB_SLAM2)
find_library(ORB_SLAM2_DBOW2_LIBRARY NAMES ORB_SLAM2_DBoW2)

find_path(ORB_SLAM2_INCLUDE_DIR NAMES ORB_SLAM2/System.h)
find_path(ORB_SLAM2_DBOW2_INCLUDE_DIR NAMES DBoW2/BowVector.h PATH_SUFFIXES ORB_SLAM2)

set(ORB_SLAM2_FOUND NO)
if(ORB_SLAM2_LIBRARY AND ORB_SLAM2_DBOW2_LIBRARY AND ORB_SLAM2_INCLUDE_DIR AND ORB_SLAM2_DBOW2_INCLUDE_DIR)
  set(ORB_SLAM2_FOUND YES)
  set(ORB_SLAM2_LIBRARIES ${ORB_SLAM2_LIBRARY} ${ORB_SLAM2_DBOW2_LIBRARY})
  set(ORB_SLAM2_INCLUDE_DIRS ${ORB_SLAM2_INCLUDE_DIR} ${ORB_SLAM2_DBOW2_INCLUDE_DIR}) 
endif(ORB_SLAM2_LIBRARY AND ORB_SLAM2_DBOW2_LIBRARY AND ORB_SLAM2_INCLUDE_DIR AND ORB_SLAM2_DBOW2_INCLUDE_DIR)
